"""Compare our COT2 data with a newer Classic World client on maplestory.io (region MCW).

maplestory.io lists MCW versions; on 2026-10-06 they were "CBT2" (matches our COT2 export exactly) and "1" (= Closed Online
Test 1: its values are the "before" side of OSMS's COT1 -> COT2 patch notes, e.g. Stirge 302 HP / 76 ATK). Neither is the
launch client yet. Check https://maplestory.io/api/wz for a new MCW version, then run this against it to see what changed
since COT2. Responses are cached in vendor/mcw/<version>/ so reruns are free.

Run:  python3 scripts/launch_diff.py [version]      (default 1)  ->  docs/launch_diff.md + build/launch_diff.json
"""
import json, pathlib, subprocess, sys, time
ROOT = pathlib.Path(__file__).resolve().parent.parent
VER = sys.argv[1] if len(sys.argv) > 1 else "1"
API = f"https://maplestory.io/api/MCW/{VER}"
CACHE = ROOT / "vendor" / "mcw" / VER
CACHE.mkdir(parents=True, exist_ok=True)
C = ROOT / "vendor" / "osms_datamine_dashboard" / "data" / "current"

def get(path, name):
    f = CACHE / name
    if not f.exists():
        for attempt in range(4):   # curl: maplestory.io answers Python's default client with 403
            r = subprocess.run(["curl", "-sS", "-m", "60", "-o", str(f), "-w", "%{http_code}", API + path], capture_output=True, text=True)
            if r.stdout == "200": break
            f.unlink(missing_ok=True)
            if attempt == 3: print("failed", path, r.stdout, r.stderr[:100]); return None
            time.sleep(2 ** attempt)
    try: return json.loads(f.read_text())
    except Exception: return None

# warm the cache with 8 parallel downloads (each item response carries its sprites, ~5 s apiece)
from concurrent.futures import ThreadPoolExecutor
def prefetch(jobs):
    with ThreadPoolExecutor(8) as ex: list(ex.map(lambda j: get(*j), jobs))

# --- monsters ---------------------------------------------------------------------------------------------------
MOB_FIELDS = [("level", "level"), ("maxHP", "hp"), ("exp", "exp"), ("physicalDamage", "PADamage"), ("physicalDefense", "PDDamage"),
              ("magicDefense", "MDDamage"), ("accuracy", "acc"), ("evasion", "eva")]
ours = {m["id"]: m for m in json.load(open(C / "monsters.json"))["monsters"]}
listing = get("/mob", "mob_list.json") or []
prefetch([(f"/mob/{r['id']}", f"mob_{r['id']}.json") for r in listing])
mob_changes, mob_new = [], []
for row in listing:
    mid = row["id"]
    d = get(f"/mob/{mid}", f"mob_{mid}.json")
    if not d: continue
    meta = d.get("meta") or {}
    if mid not in ours: mob_new.append([mid, d.get("name"), meta.get("level")]); continue
    o = ours[mid]; diff = {}
    for theirs, mine in MOB_FIELDS:
        a, b = o.get(mine), meta.get(theirs)
        if a is not None and b is not None and a != b: diff[theirs] = [a, b]
    if diff: mob_changes.append([mid, o["name"], o.get("level"), diff])
mob_gone = [[i, m["name"]] for i, m in ours.items() if i not in {r["id"] for r in listing}]

# --- weapons ----------------------------------------------------------------------------------------------------
items = json.load(open(C / "items.json"))
weapons = {i["id"]: i for i in items["items"] if i.get("sub_category") == "Weapon"}
W_FIELDS = [("reqLevel", "reqLevel"), ("reqSTR", "reqSTR"), ("reqDEX", "reqDEX"), ("reqINT", "reqINT"), ("reqLUK", "reqLUK"),
            ("incPAD", "incPAD"), ("incMAD", "incMAD"), ("attackSpeed", "attackSpeed"), ("tuc", "tuc")]
w_changes, w_missing = [], []
prefetch([(f"/item/{wid}", f"item_{wid}.json") for wid in weapons])
for wid, w in sorted(weapons.items()):
    d = get(f"/item/{wid}", f"item_{wid}.json")
    if not d or "metaInfo" not in d: w_missing.append([wid, w["name"]]); continue
    meta, st, diff = d["metaInfo"], w.get("stats") or {}, {}
    for theirs, mine in W_FIELDS:
        a, b = st.get(mine, 0) or 0, meta.get(theirs, 0) or 0
        if a != b: diff[theirs] = [a, b]
    if diff: w_changes.append([wid, w["name"], diff])

out = {"version": VER, "source": API, "mobs_compared": len(listing), "mob_changes": mob_changes, "mob_new": mob_new, "mob_gone": mob_gone,
       "weapons_compared": len(weapons) - len(w_missing), "weapon_changes": w_changes, "weapon_missing": w_missing}
(ROOT / "build").mkdir(exist_ok=True)
(ROOT / "build" / "launch_diff.json").write_text(json.dumps(out, indent=1))

def fmtdiff(d): return ", ".join(f"{k} {a} → {b}" for k, (a, b) in d.items())
KNOWN = {"1": "MCW 1 is Closed Online Test 1 (older than our COT2 data; matches the 'before' side of OSMS's COT1 -> COT2 patch notes), so this lists COT1 -> COT2 changes, not launch changes.",
         "CBT2": "MCW CBT2 matches our COT2 export."}
lines = [f"# COT2 vs maplestory.io MCW version {VER}", "",
         f"Generated by `scripts/launch_diff.py {VER}`. Ours = OSMS COT2 export; theirs = {API}. Arrows read ours → theirs.", "",
         KNOWN.get(VER, "Newer version: these are changes since COT2. Re-check the page's numbers against them."), "",
         f"- Monsters compared: {len(listing)}; changed: {len(mob_changes)}; new: {len(mob_new)}; ours not in theirs: {len(mob_gone)}",
         f"- Weapons compared: {out['weapons_compared']}; changed: {len(w_changes)}; not found there: {len(w_missing)}", "",
         "## Monsters changed", "", "| Monster | Lv | Changes |", "|---|---|---|"]
lines += [f"| {n} ({i}) | {lv} | {fmtdiff(d)} |" for i, n, lv, d in sorted(mob_changes, key=lambda x: x[2] or 0)]
if mob_new: lines += ["", "## Monsters new in this version", ""] + [f"- {n} ({i}), Lv {lv}" for i, n, lv in mob_new]
if mob_gone: lines += ["", "## Monsters not in this version", ""] + [f"- {n} ({i})" for i, n in mob_gone]
lines += ["", "## Weapons changed", "", "| Weapon | Changes |", "|---|---|"] + [f"| {n} ({i}) | {fmtdiff(d)} |" for i, n, d in w_changes]
(ROOT / "docs" / "launch_diff.md").write_text("\n".join(lines) + "\n")
print(f"MCW {VER}: {len(mob_changes)} monsters changed, {len(mob_new)} new, {len(mob_gone)} missing; {len(w_changes)} weapons changed, {len(w_missing)} not found")
